---
Name: ecommerce_stockcontrol
Before: 'mysite/*'
After: 'framework/*','cms/*', 'ecommerce/*'
---

Product:
  extensions:
    - BuyableStockDecorator


BuyableStockDecorator:
  buyables:
    - Product
